# Generated by Django 4.2.1 on 2023-06-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_images_customuser_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verified',
        ),
    ]
