# Generated by Django 4.2.1 on 2023-06-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_sale_price'),
        ('orders', '0004_remove_orderitem_order_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(to='main.product'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
